Repository SOPT-all/36-COLLABORATION-iOS-ALARMY, pull requests merged in 2025-05, with the labels that each got.

#5 [Docs/#1] 깃 이그노어
  .gitignore
  Alarmy-iOS/Alarmy-iOS.xcodeproj/project.pbxproj
Labels: 🐿️ 주리, SETTING

#7 [Add/#4] 아이콘 및 사진 asset 추가
  .DS_Store
  Alarmy-iOS/Alarmy-iOS.xcodeproj/project.xcworkspace/xcuserdata/oeunji.xcuserdatad/UserInterfaceState.xcuserstate
  Alarmy-iOS/Alarmy-iOS.xcodeproj/xcuserdata/oeunji.xcuserdatad/xcschemes/xcschememanagement.plist
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/Contents.json
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icn_setting_close.imageset/Contents.json
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icn_setting_close.imageset/icn_setting_close.svg
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icn_setting_lock.imageset/Contents.json
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icn_setting_lock.imageset/icn_setting_lock.svg
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icn_setting_sound_off.imageset/Contents.json
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icn_setting_sound_off.imageset/icn_setting_sound_off.svg
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icn_setting_sound_on.imageset/Contents.json
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icn_setting_sound_on.imageset/icn_setting_sound_on.svg
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icon_alarm_menu.imageset/Contents.json
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icon_alarm_menu.imageset/icon_alarm_menu.svg
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icon_alarm_null.imageset/Contents.json
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icon_alarm_null.imageset/icon_alarm_null.svg
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icon_floating_clock.imageset/Contents.json
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icon_floating_clock.imageset/icon_floating_clock.svg
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icon_floating_close.imageset/Contents.json
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icon_floating_close.imageset/icon_floating_close.svg
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icon_floating_med.imageset/Contents.json
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icon_floating_med.imageset/icon_floating_med.svg
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icon_floating_plus.imageset/Contents.json
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icon_floating_plus.imageset/icon_floating_plus.svg
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icon_floating_quick.imageset/Contents.json
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icon_floating_quick.imageset/icon_floating_quick.svg
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icon_gnb_clockoff.imageset/Contents.json
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icon_gnb_clockoff.imageset/icon_gnb_clockoff.svg
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icon_gnb_clockon.imageset/Contents.json
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icon_gnb_clockon.imageset/icon_gnb_clockon.svg
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icon_gnb_morningoff.imageset/Contents.json
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icon_gnb_morningoff.imageset/icon_gnb_morningoff.svg
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icon_gnb_morningon.imageset/Contents.json
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icon_gnb_morningon.imageset/icon_gnb_morningon.svg
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icon_gnb_report.imageset/Contents.json
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icon_gnb_report.imageset/icon_gnb_report.svg
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icon_gnb_setting.imageset/Contents.json
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icon_gnb_setting.imageset/icon_gnb_setting.svg
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icon_gnb_sleep.imageset/Contents.json
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icon_gnb_sleep.imageset/icon_gnb_sleep.svg
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icon_header_menu.imageset/Contents.json
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icon_header_menu.imageset/icon_header_menu.svg
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icon_morning_cloud.imageset/Contents.json
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icon_morning_cloud.imageset/icon_morning_cloud.svg
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icon_morning_mood.imageset/Contents.json
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icon_morning_mood.imageset/icon_morning_mood.svg
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icon_morning_rain.imageset/Contents.json
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icon_morning_rain.imageset/icon_morning_rain.svg
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icon_morning_sun.imageset/Contents.json
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icon_morning_sun.imageset/icon_morning_sun.svg
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/image/Contents.json
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/image/morningBackground.imageset/Contents.json
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/image/morningBackground.imageset/morning_background_ios.png
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/image/morningBackground.imageset/morning_background_ios@2x.png
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/image/morningBackground.imageset/morning_background_ios@3x.png
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/image/stopBackground.imageset/Contents.json
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/image/stopBackground.imageset/stop_background_ios.png
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/image/stopBackground.imageset/stop_background_ios@2x.png
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/image/stopBackground.imageset/stop_background_ios@3x.png
Labels: ADD

#9 [Add/#6] 컬러 에셋 추가
  Alarmy-iOS/Alarmy-iOS/Resource/Extension/UIColor+.swift
Labels: 🐿️ 주리, ADD

#10 [Style/#8] 하단 탭 바 만들기
  Alarmy-iOS/Alarmy-iOS.xcodeproj/project.xcworkspace/xcuserdata/oeunji.xcuserdatad/UserInterfaceState.xcuserstate
  Alarmy-iOS/Alarmy-iOS/App/SceneDelegate.swift
  Alarmy-iOS/Alarmy-iOS/Presentation/AlarmyTabBarController.swift
  Alarmy-iOS/Alarmy-iOS/Presentation/SubViews/AlarmViewController.swift
  Alarmy-iOS/Alarmy-iOS/Presentation/SubViews/MorningViewController.swift
Labels: 🐰 은지, STYLE

#11 [Setting/#3] 폰트 추가 및 extension 구현
  .DS_Store
  Alarmy-iOS/Alarmy-iOS.xcodeproj/project.xcworkspace/xcuserdata/seojooyoung.xcuserdatad/UserInterfaceState.xcuserstate
  Alarmy-iOS/Alarmy-iOS.xcodeproj/xcuserdata/seojooyoung.xcuserdatad/xcschemes/xcschememanagement.plist
  Alarmy-iOS/Alarmy-iOS/Resource/Extension/UIFont+.swift
  Alarmy-iOS/Alarmy-iOS/Resource/Fonts/Pretendard-Bold.otf
  Alarmy-iOS/Alarmy-iOS/Resource/Fonts/Pretendard-Medium.otf
  Alarmy-iOS/Alarmy-iOS/Resource/Fonts/Pretendard-Regular.otf
  Alarmy-iOS/Alarmy-iOS/Resource/Fonts/Pretendard-SemiBold.otf
  Alarmy-iOS/Alarmy-iOS/Resource/Info.plist
Labels: 🐶 주영, SETTING

#18 [Setting/#17] extension 추가
  Alarmy-iOS/Alarmy-iOS/Resource/Extension/UIImage+.swift
  Alarmy-iOS/Alarmy-iOS/Resource/Extension/UIStackView+.swift
  Alarmy-iOS/Alarmy-iOS/Resource/Extension/UIView+.swift
Labels: 🐿️ 주리, SETTING

#20 [Docs/#20] .DS_Store 추가
  .gitignore
Labels: 🐰 은지, DOCS

#25 [Style/#19] 홈 UI
  Alarmy-iOS/Alarmy-iOS.xcodeproj/project.xcworkspace/xcuserdata/oeunji.xcuserdatad/UserInterfaceState.xcuserstate
  Alarmy-iOS/Alarmy-iOS/Network/Model/AlarmModel.swift
  Alarmy-iOS/Alarmy-iOS/Presentation/SubViews/AlarmViewController.swift
  Alarmy-iOS/Alarmy-iOS/Presentation/SubViews/View/AlarmCollectionHeaderView.swift
  Alarmy-iOS/Alarmy-iOS/Presentation/SubViews/View/AlarmCollectionView.swift
  Alarmy-iOS/Alarmy-iOS/Presentation/SubViews/View/AlarmCollectionViewCell.swift
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/boolean_home_off.imageset/Contents.json
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/boolean_home_off.imageset/boolean_home_off.svg
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/boolean_home_on.imageset/Contents.json
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/boolean_home_on.imageset/boolean_home_on.svg
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icn_home_sound.imageset/Contents.json
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icn_home_sound.imageset/icn_home_sound_ios.png
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icn_home_sound.imageset/icn_home_sound_ios@2x.png
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icn_home_sound.imageset/icn_home_sound_ios@3x.png
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icon_alarm_menu_off.imageset/Contents.json
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icon_alarm_menu_off.imageset/icon_alarm_menu_ios.svg
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icon_alarm_menu_on.imageset/Contents.json
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icon_alarm_menu_on.imageset/icon_alarm_menu.svg
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icon_alarm_null_off.imageset/Contents.json
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icon_alarm_null_off.imageset/icon_alarm_null_off.svg
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icon_alarm_null_on.imageset/Contents.json
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icon_alarm_null_on.imageset/icon_alarm_null.svg
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icon_home_arrow.imageset/Contents.json
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icon_home_arrow.imageset/icon_home_arrow.svg
Labels: 🐰 은지, STYLE, ADD

#16 [Setting/#14] 네트워크 세팅
  Alarmy-iOS/Alarmy-iOS.xcodeproj/project.pbxproj
  Alarmy-iOS/Alarmy-iOS/Network/Base/BaseResponse.swift
  Alarmy-iOS/Alarmy-iOS/Network/Base/BaseService.swift
  Alarmy-iOS/Alarmy-iOS/Network/Base/EndPoint.swift
  Alarmy-iOS/Alarmy-iOS/Network/Base/HTTPMethodType.swift
  Alarmy-iOS/Alarmy-iOS/Network/Base/NetworkError.swift
  Alarmy-iOS/Alarmy-iOS/Network/Base/NetworkLogger.swift
  Alarmy-iOS/Alarmy-iOS/Network/Model/TempModel.swift
  Alarmy-iOS/Alarmy-iOS/Network/Service/TempService.swift
  Alarmy-iOS/Alarmy-iOS/Resource/Info.plist
Labels: 🐿️ 주리, SETTING, FEAT

#24 [Style/#15] 알람 설정 UI 구현
  .DS_Store
  .gitignore
  Alarmy-iOS/Alarmy-iOS.xcodeproj/project.pbxproj
  Alarmy-iOS/Alarmy-iOS.xcodeproj/project.xcworkspace/xcuserdata/seojooyoung.xcuserdatad/UserInterfaceState.xcuserstate
  Alarmy-iOS/Alarmy-iOS/App/SceneDelegate.swift
  Alarmy-iOS/Alarmy-iOS/Presentation/AlarmSetting/View/AlarmSettingView.swift
  Alarmy-iOS/Alarmy-iOS/Presentation/AlarmSetting/View/EtcSettingView.swift
  Alarmy-iOS/Alarmy-iOS/Presentation/AlarmSetting/View/HeaderView.swift
  Alarmy-iOS/Alarmy-iOS/Presentation/AlarmSetting/View/MissionSettingView.swift
  Alarmy-iOS/Alarmy-iOS/Presentation/AlarmSetting/View/SoundSettingView.swift
  Alarmy-iOS/Alarmy-iOS/Presentation/AlarmSetting/View/TimeAndDaySettingView.swift
  Alarmy-iOS/Alarmy-iOS/Presentation/AlarmSetting/ViewController/AlarmSettingViewController.swift
  Alarmy-iOS/Alarmy-iOS/Presentation/Component/AlarmSetting/DayButton.swift
  Alarmy-iOS/Alarmy-iOS/Presentation/Component/AlarmSetting/MoreButton.swift
  Alarmy-iOS/Alarmy-iOS/Presentation/Component/AlarmSetting/SectionDivider.swift
  Alarmy-iOS/Alarmy-iOS/Presentation/SubViews/MissionCollectionViewCell.swift
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/button/Contents.json
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/button/btn_setting_checkbox.imageset/Checkbox 1.png
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/button/btn_setting_checkbox.imageset/Checkbox 2.png
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/button/btn_setting_checkbox.imageset/Checkbox.png
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/button/btn_setting_checkbox.imageset/Contents.json
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/button/btn_setting_empty_checkbox.imageset/Contents.json
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/button/btn_setting_empty_checkbox.imageset/checkbox1x.png
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/button/btn_setting_empty_checkbox.imageset/checkbox2x.png
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/button/btn_setting_empty_checkbox.imageset/checkbox3x.png
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/button/btn_setting_mission_dotted.imageset/Contents.json
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/button/btn_setting_mission_dotted.imageset/btn_mission1x.png
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/button/btn_setting_mission_dotted.imageset/btn_mission2x.png
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/button/btn_setting_mission_dotted.imageset/btn_mission3x.png
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/button/btn_setting_mission_solid.imageset/Contents.json
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/button/btn_setting_mission_solid.imageset/btn_mission1x.png
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/button/btn_setting_mission_solid.imageset/btn_mission2x.png
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/button/btn_setting_mission_solid.imageset/btn_mission3x.png
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/button/btn_setting_more.imageset/Contents.json
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/button/btn_setting_more.imageset/moreButton1x.png
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/button/btn_setting_more.imageset/moreButton2x.png
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/button/btn_setting_more.imageset/moreButton3x.png
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/button/btn_setting_vibration_false.imageset/Contents.json
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/button/btn_setting_vibration_false.imageset/vibration_false1x.png
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/button/btn_setting_vibration_false.imageset/vibration_false2x.png
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/button/btn_setting_vibration_false.imageset/vibration_false3x.png
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/button/btn_setting_vibration_true.imageset/Contents.json
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/button/btn_setting_vibration_true.imageset/vibration_true1x.png
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/button/btn_setting_vibration_true.imageset/vibration_true2x.png
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/button/btn_setting_vibration_true.imageset/vibration_true3x.png
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icn_setting_slider_thumb.imageset/Contents.json
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icn_setting_slider_thumb.imageset/sliderThumb1x.png
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icn_setting_slider_thumb.imageset/sliderThumb2x.png
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icn_setting_slider_thumb.imageset/sliderThumb3x.png
Labels: 🐶 주영, STYLE

#22 [Style/#12] 알람 끄기 UI
  Alarmy-iOS/Alarmy-iOS/Presentation/OffAlarm/View/OffAlarmView.swift
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/icon/icon_home_arrow.imageset/Property 1=Right.svg
  Alarmy-iOS/Alarmy-iOS/Resource/Extension/CALayer+.swift
Labels: 🐿️ 주리, STYLE

#29 [Style#23] 플로팅 버튼 만들기 ~
  Alarmy-iOS/Alarmy-iOS/App/SceneDelegate.swift
  Alarmy-iOS/Alarmy-iOS/Presentation/ViewController/AlarmViewController.swift
  Alarmy-iOS/Alarmy-iOS/Presentation/ViewController/View/AlarmCircleButton.swift
Labels: 🐿️ 주리, STYLE

#31 [Feature/#28] 알람 설정 뷰 HeaderView 기능 구현
  Alarmy-iOS/Alarmy-iOS.xcodeproj/project.xcworkspace/xcuserdata/seojooyoung.xcuserdatad/UserInterfaceState.xcuserstate
  Alarmy-iOS/Alarmy-iOS/Presentation/AlarmSetting/View/AlarmSettingView.swift
  Alarmy-iOS/Alarmy-iOS/Presentation/AlarmSetting/View/EtcSettingView.swift
  Alarmy-iOS/Alarmy-iOS/Presentation/AlarmSetting/View/HeaderView.swift
  Alarmy-iOS/Alarmy-iOS/Presentation/AlarmSetting/View/MissionSettingView.swift
  Alarmy-iOS/Alarmy-iOS/Presentation/AlarmSetting/View/SoundSettingView.swift
  Alarmy-iOS/Alarmy-iOS/Presentation/AlarmSetting/View/TimeAndDaySettingView.swift
Labels: 🐶 주영, FEAT

#33 [Feat/#30] 아침 api 붙이기
  Alarmy-iOS/Alarmy-iOS.xcodeproj/project.pbxproj
  Alarmy-iOS/Alarmy-iOS/Network/Base/BaseService.swift
  Alarmy-iOS/Alarmy-iOS/Network/Base/EndPoint.swift
  Alarmy-iOS/Alarmy-iOS/Network/Base/HTTPMethodType.swift
  Alarmy-iOS/Alarmy-iOS/Network/Model/QuoteResponse.swift
  Alarmy-iOS/Alarmy-iOS/Network/Model/WeatherResponse.swift
  Alarmy-iOS/Alarmy-iOS/Network/Service/MorningService.swift
  Alarmy-iOS/Alarmy-iOS/Network/Service/TempService.swift
  Alarmy-iOS/Alarmy-iOS/Presentation/Morning/Model/WeatherEntity.swift
  Alarmy-iOS/Alarmy-iOS/Presentation/Morning/Model/WeatherIcon.swift
  Alarmy-iOS/Alarmy-iOS/Presentation/Morning/View/Morning/HeaderInformationView.swift
  Alarmy-iOS/Alarmy-iOS/Presentation/Morning/View/Morning/MorningView.swift
  Alarmy-iOS/Alarmy-iOS/Presentation/Morning/View/Morning/TodaySentenceView.swift
  Alarmy-iOS/Alarmy-iOS/Presentation/Morning/ViewController/MorningViewController.swift
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/image/quote1.imageset/Contents.json
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/image/quote1.imageset/img_today_quote1_ios.png
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/image/quote1.imageset/img_today_quote1_ios@2x.png
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/image/quote1.imageset/img_today_quote1_ios@3x.png
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/image/quote2.imageset/Contents.json
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/image/quote2.imageset/img_today_quote2_ios.png
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/image/quote2.imageset/img_today_quote2_ios@2x.png
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/image/quote2.imageset/img_today_quote2_ios@3x.png
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/image/quote3.imageset/Contents.json
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/image/quote3.imageset/img_today_quote3_ios.png
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/image/quote3.imageset/img_today_quote3_ios@2x.png
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/image/quote3.imageset/img_today_quote3_ios@3x.png
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/image/quote4.imageset/Contents.json
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/image/quote4.imageset/img_today_quote4_ios.png
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/image/quote4.imageset/img_today_quote4_ios@2x.png
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/image/quote4.imageset/img_today_quote4_ios@3x.png
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/image/quote5.imageset/Contents.json
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/image/quote5.imageset/img_today_quote5_ios.png
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/image/quote5.imageset/img_today_quote5_ios@2x.png
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/image/quote5.imageset/img_today_quote5_ios@3x.png
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/image/quote6.imageset/Contents.json
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/image/quote6.imageset/img_today_quote6_ios.png
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/image/quote6.imageset/img_today_quote6_ios@2x.png
  Alarmy-iOS/Alarmy-iOS/Resource/Assets.xcassets/image/quote6.imageset/img_today_quote6_ios@3x.png
  Alarmy-iOS/Alarmy-iOS/Resource/Extension/Bundle+.swift
Labels: 🐿️ 주리, FEAT

#35 [Feat/#32] 알람 전체 조회 api 연결
  Alarmy-iOS/Alarmy-iOS.xcodeproj/project.pbxproj
  Alarmy-iOS/Alarmy-iOS.xcodeproj/project.xcworkspace/xcuserdata/oeunji.xcuserdatad/UserInterfaceState.xcuserstate
  Alarmy-iOS/Alarmy-iOS/Network/Base/EndPoint.swift
  Alarmy-iOS/Alarmy-iOS/Network/Model/AlarmModel.swift
  Alarmy-iOS/Alarmy-iOS/Network/Model/AlarmResponse.swift
  Alarmy-iOS/Alarmy-iOS/Network/Service/AlarmService.swift
  Alarmy-iOS/Alarmy-iOS/Presentation/Alarm/Model/AlarmEntity.swift
  Alarmy-iOS/Alarmy-iOS/Presentation/Alarm/View/AlarmCircleButton.swift
  Alarmy-iOS/Alarmy-iOS/Presentation/Alarm/View/AlarmCollectionHeaderView.swift
  Alarmy-iOS/Alarmy-iOS/Presentation/Alarm/View/AlarmCollectionView.swift
  Alarmy-iOS/Alarmy-iOS/Presentation/Alarm/View/AlarmCollectionViewCell.swift
  Alarmy-iOS/Alarmy-iOS/Presentation/Alarm/ViewController/AlarmViewController.swift
  Alarmy-iOS/Alarmy-iOS/Resource/Info.plist
Labels: 🐰 은지, FEAT

#37 [Feat/#34] 알람 생성 api 연결
  .DS_Store
  Alarmy-iOS/Alarmy-iOS.xcodeproj/project.pbxproj
  Alarmy-iOS/Alarmy-iOS.xcodeproj/project.xcworkspace/xcuserdata/juri.xcuserdatad/UserInterfaceState.xcuserstate
  Alarmy-iOS/Alarmy-iOS.xcodeproj/project.xcworkspace/xcuserdata/oeunji.xcuserdatad/UserInterfaceState.xcuserstate
  Alarmy-iOS/Alarmy-iOS.xcodeproj/project.xcworkspace/xcuserdata/seojooyoung.xcuserdatad/UserInterfaceState.xcuserstate
  Alarmy-iOS/Alarmy-iOS.xcodeproj/xcuserdata/juri.xcuserdatad/xcschemes/xcschememanagement.plist
  Alarmy-iOS/Alarmy-iOS.xcodeproj/xcuserdata/oeunji.xcuserdatad/xcschemes/xcschememanagement.plist
  Alarmy-iOS/Alarmy-iOS.xcodeproj/xcuserdata/seojooyoung.xcuserdatad/xcschemes/xcschememanagement.plist
  Alarmy-iOS/Alarmy-iOS/Network/Base/EndPoint.swift
  Alarmy-iOS/Alarmy-iOS/Network/Model/AlarmSettingModel.swift
  Alarmy-iOS/Alarmy-iOS/Network/Service/AlarmSettingService.swift
  Alarmy-iOS/Alarmy-iOS/Presentation/Alarm/ViewController/AlarmViewController.swift
  Alarmy-iOS/Alarmy-iOS/Presentation/AlarmSetting/Cell/MissionCollectionViewCell.swift
  Alarmy-iOS/Alarmy-iOS/Presentation/AlarmSetting/View/AlarmSettingView.swift
  Alarmy-iOS/Alarmy-iOS/Presentation/AlarmSetting/View/HeaderView.swift
  Alarmy-iOS/Alarmy-iOS/Presentation/AlarmSetting/View/TimeAndDaySettingView.swift
  Alarmy-iOS/Alarmy-iOS/Presentation/AlarmSetting/ViewController/AlarmSettingViewController.swift
Labels: 🐶 주영, FEAT

#40 [Bug/#39] 알람 끄기 뷰 버그 수정
  Alarmy-iOS/Alarmy-iOS/Network/Base/EndPoint.swift
  Alarmy-iOS/Alarmy-iOS/Presentation/Alarm/ViewController/AlarmViewController.swift
Labels: 🐶 주영, BUG
